version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: package.json
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn lint:ci
